server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/pokedex
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      host: localhost
      port: 27017
      database: pokedex

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

appDescription: "Pokedex API"
appVersion: "1.0.0"