spring:
  application:
    name: Gateway

  #Gateway Configuration Properties
  cloud:
    gateway:
      routes:
        - id: pokemon-microservice
          uri: lb://pokemon/**
          predicates:
            - Path=/pokemon/**
        - id: image-microservice
          uri: lb://image/**
          predicates:
            - Path=/images/**

#Tomcat Embedded Server Configuration
server:
  port: 7000

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka